version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  pre_build:
    commands:
      - git show-refs --tags
      # - command
    #finally:
      # - command
      # - command
  #build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  post_build:
    commands:
      - ls -l $CODEBUILD_SRC_DIR/
      #- aws s3 sync / s3://pythontest832/
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path